Added sequence uploader
cognitedata/python-extractor-utils pull request #66
Opened 2020-09-03 06:19 UTC by thomafred

2020-09-03 11:23 UTC, mathialo requested changes
Great addition! 

See comments for a couple of thoughts on consistency with the rest of the library. Would also be great with either a unit or an integration test.

It also seems that `black` is complaining about the format, a simple `poetry run black` should fix that :)

2020-09-03 11:23 UTC, mathialo commented on cognite/extractorutils/uploader.py
> +        self._create_or_update(either_id)
Calling this every time will double the amount of API requests, slowing down the extractor.

The pattern used elsewhere is to call the insert method, and create the sequence on an error. This reduces the amount of requests with quite a bit.

2020-09-03 11:23 UTC, mathialo commented on cognite/extractorutils/uploader.py
> +    def __init__(
The `TimeSeriesUploadQueue` has a `create_missing` option to enable the automatic creation of missing time series. For consistency, I suggest adding that as an option here as well, and leave it off by default.

2020-09-04 05:53 UTC, thomafred commented
I have made the requested changes, however the TimeSeries integration tests are failing due to missing API key. I do not have access to an environment where I can run these tests.

2020-09-04 07:19 UTC, mathialo commented
> I have made the requested changes, however the TimeSeries integration tests are failing due to missing API key. I do not have access to an environment where I can run these tests.

Nice! Thanks a lot for the contribution.

No worries, that's a known issue for PRs on this repo. The tests will pass on master 🙂

2020-09-04 07:20 UTC, merged